name: ItemSzop Plugin
version: '${version}'
main: com.github.michaljaz.itemszop.Itemszop
api-version: 1.15
description: Plugin do wywoływania komend na serwerze z bazy firebase
website: https://itemszop.tk
